---
- hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks: 
  - name: Set timezone 
    timezone:
      name: Asia/Tokyo
  - name: Check locale
    command: localectl status
    register: localectl_result
    check_mode: no
    changed_when: false
  - name: Set environment 
    command: "{{ item }}"
    loop:
      - localectl set-locale LANG=ja_JP.utf8
      - localectl set-keymap jp106
      - hostnamectl set-hostname AlmaLinux
    when: "'LANG=ja_JP.utf8' not in localectl_result.stdout"
  - name: Development tools install
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - telnet
        - wget
        - perl
        - perl-CGI
        - vim
        - bind-utils
        - "@Development tools"
  - name: Add alias vim
    lineinfile: dest={{ item }} line="alias vi='vim'"
    loop:
      - /root/.bashrc
  - name: Selinux disabled
    selinux:
       policy: targeted
       state: disabled
  - name: Disabled service firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no
  - name: Install ntpd(chrony) 
    yum:
      name: chrony
  - name: copu chrony conf-file
    copy:
      src: vars/chrony.conf
      dest: /etc/chrony.conf
      mode: 644
      owner: root
      group: root
  - name: Enable service ntpd(chrony)
    systemd:
      name: chronyd
      state: started
      enabled: yes
  - name: Yum update
    yum:
       name: '*'
       state: latest
  - name: Install WebServer
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - httpd
        - mod_ssl
  - name: Checked Install PHP
    yum:
      list: php
    register: result_php_installed
  - name: Install PHP
    command: dnf module install -y php:7.4
    when: result_php_installed.results | selectattr("yumstate", "match", "installed") | list | length == 0
  - name: Install PHP
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - php
        - php-common
        - php-gd
        - php-pdo
        - php-mysqlnd
        - php-mbstring
        - php-xml
        - php-bcmath
        - php-pear
  - name: Install MariaDB
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - mariadb
        - mariadb-server
        - python3-PyMySQL
  - name: Enable service web
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - httpd      
      - php-fpm
      - mariadb
  - name: root アカウントのパスワードを設定
    mysql_user:
      name: root
      host: localhost
      password: "rootpass"
  - name: rootユーザのパスワード設定
    no_log: true
    mysql_user:
      login_user: "root"
      login_password: "rootpass"
      name: "root"
      password: "rootpass"
      check_implicit_admin: yes
      state: present
  - name: データベースを作成
    mysql_db:
      login_user: root
      login_password: "rootpass"
      name: "db_name"
      state: present
  - name: MySQLユーザーを作成しすべての権限を与える
    no_log: true
    mysql_user:
      login_user: root
      login_password: "rootpass"
      name: "db_user"
      password: "db_pass"
      priv: "db_name.*:ALL"
      host: localhost
      state: present